version: '3.8'

services:
  spring-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cerbo_database
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cerbo_database
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
